# Generated by Django 3.2.6 on 2021-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='buyer',
            field=models.CharField(default='buyer', max_length=100),
        ),
        migrations.AddField(
            model_name='sell',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sell',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell',
            name='product_title',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sell',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
