# Generated by Django 3.2.6 on 2021-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210828_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='product_title',
            field=models.CharField(max_length=100),
        ),
    ]
