# Generated by Django 3.2.3 on 2021-08-28 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_sell_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
