# Generated by Django 3.2.3 on 2021-08-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='tolal',
            new_name='total',
        ),
    ]
