# Generated by Django 3.2.6 on 2021-08-31 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_tolal_accounts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
